import pytest

from worker import worker
from worker.daemon import main


def _contract(owner, capability, scenario):
    value = getattr(owner, capability, None)
    assert callable(value), f"{scenario}: retained DevBox contract requires {owner.__name__}.{capability}"


TASK_CONTRACTS = [
    (worker, "launch_task", "task_conflict_is_rejected"),
    (worker, "launch_task_idempotent", "task_launch_is_idempotent"),
    (main.Runtime, "recover", "task_sequence_survives_restart"),
    (worker, "answer_question", "answered_attention_resyncs"),
    (worker, "fail_task", "errored_state_carries_reason"),
    (worker, "complete_task", "complete_transition_carries_result"),
    (worker, "ask_question", "attention_transition_carries_question"),
    (worker, "answer_question", "answer_retires_question"),
    (worker, "complete_task", "task_that_never_asked_has_no_question_result"),
    (worker, "complete_task_atomic", "complete_commits_result_and_status_together"),
    (worker, "complete_task_atomic", "complete_rolls_back_result_when_status_write_fails"),
    (worker, "record_input", "launch_prompt_is_first_recorded_input"),
    (worker, "allocate_event_sequence", "concurrent_event_writers_allocate_unique_sequences"),
    (worker, "allocate_event_sequence", "event_sequence_reseeds_after_external_writer"),
    (worker, "allocate_event_sequence", "event_sequence_resumes_after_restart"),
    (worker, "send_task_input", "task_input_endpoint_guards_auth_and_ownership"),
    (worker, "send_task_input", "task_input_requires_durable_store"),
    (worker, "record_input", "task_input_is_recorded"),
    (worker, "send_task_input", "task_input_store_gate_is_atomic"),
    (worker, "watch_task", "task_watch_streams_transitions"),
    (worker, "watch_task", "task_watch_replays_then_streams_live"),
    (worker, "watch_task", "task_watch_terminal_task_replays_terminal_frame"),
    (worker, "watch_task", "task_watch_resumes_after_cursor"),
    (worker, "watch_task", "task_watch_missing_task_is_not_found"),
    (worker, "watch_task", "task_watch_guards_auth_and_ownership"),
    (main.Runtime, "deliver_pending_input", "pending_input_types_into_live_agent"),
    (main.Runtime, "deliver_pending_input", "pending_input_relaunches_dead_agent"),
    (worker, "send_task_input", "pending_input_wakes_completed_task"),
    (worker, "answer_question", "pending_input_answers_attention"),
    (main.Runtime, "build_workspace", "first_launch_builds_workspace_from_prompt"),
    (main.Runtime, "deliver_pending_input", "input_queued_behind_kickoff_is_delivered"),
    (main.Runtime, "launch_recorded_task", "pre_recorded_prompt_is_accepted"),
    (main.Runtime, "launch_recorded_task", "missing_first_prompt_errors_task"),
    (main.Runtime, "deliver_pending_input", "input_retries_after_launch_failure"),
    (main.Runtime, "deliver_pending_input", "queued_inputs_are_concatenated"),
    (main.Runtime, "deliver_pending_input", "only_pending_input_is_sent"),
    (main.Runtime, "deliver_pending_input", "oversized_input_batch_is_split"),
    (main.Runtime, "deliver_pending_input", "pending_batch_always_sends_one"),
    (main.Runtime, "deliver_pending_input", "errored_task_does_not_receive_input"),
    (worker, "ask_question", "duplicate_question_reports_already_parked"),
    (worker, "answer_question", "input_handoff_retires_question_without_state_edge"),
    (worker, "answer_question", "input_handoff_without_question_is_quiet"),
    (worker, "ask_question", "question_is_carried_by_attention_state"),
    (worker, "delete_task", "task_inputs_cascade_with_task"),
    (worker, "reconcile_task", "pending_task_launches"),
    (worker, "reconcile_task", "pending_launch_error_is_recorded"),
    (worker, "reconcile_task", "running_task_can_await_input"),
    (worker, "reconcile_task", "trailing_tool_call_does_not_mask_attention"),
    (worker, "reconcile_task", "answered_attention_runs_again"),
    (worker, "reconcile_task", "answer_clears_attention"),
    (worker, "reconcile_task", "input_reactivates_complete_task"),
    (worker, "reconcile_task", "complete_ignores_trailing_turn_output"),
    (worker, "reconcile_task", "complete_stays_complete"),
    (worker, "reconcile_task", "restore_does_not_reactivate_complete_task"),
    (worker, "reconcile_task", "busy_running_task_is_not_stuck"),
    (worker, "reconcile_task", "stuck_running_task_is_detected"),
    (worker, "reconcile_task", "fresh_launch_without_events_is_not_stuck"),
    (worker, "reconcile_task", "fresh_no_event_task_stays_running"),
    (worker, "reconcile_task", "complete_task_finalizes"),
    (worker, "reconcile_task", "complete_can_finalize_while_session_lives"),
    (worker, "reconcile_task", "fatal_error_wins_while_session_lives"),
    (worker, "reconcile_task", "answered_task_flips_to_running"),
    (worker, "reconcile_task", "attention_can_complete"),
    (worker, "reconcile_task", "completion_survives_trailing_noise"),
    (worker, "reconcile_task", "open_tool_call_keeps_task_running"),
    (worker, "reconcile_task", "resolved_tool_calls_allow_parking"),
    (worker, "reconcile_task", "orphaned_old_call_does_not_hold_turn_open"),
    (worker, "reconcile_task", "woken_task_with_real_question_stays_attention"),
    (worker, "reconcile_task", "woken_task_with_new_completion_finalizes"),
    (worker, "reconcile_task", "fatal_agent_error_errors_task"),
    (worker, "reconcile_task", "dead_session_is_resumed"),
    (worker, "reconcile_task", "blocked_agent_is_restored_not_resumed"),
    (worker, "reconcile_task", "answered_attention_resumes_dead_session"),
    (worker, "reconcile_task", "stuck_task_resumes"),
    (worker, "reconcile_task", "missing_history_starts_fresh"),
    (worker, "reconcile_task", "user_input_is_not_resumable_agent_history"),
    (worker, "reconcile_task", "retry_can_then_enter_attention"),
    (worker, "subscribe_task", "state_transitions_are_published"),
    (worker, "watch_task", "event_tail_emits"),
    (worker, "reconcile_task", "failed_launch_record_stops_leftover_agent"),
    (worker, "reconcile_task", "complete_survives_post_grace_activity"),
    (worker, "reconcile_task", "complete_with_open_call_runs_again"),
    (worker, "answer_question", "only_answer_clears_attention"),
    (worker, "park_task", "attention_barrier_carries_last_words"),
    (worker, "park_task", "parking_records_one_barrier_per_park"),
    (worker, "park_task", "explicit_question_does_not_get_second_barrier"),
    (worker, "park_task", "silent_agent_still_records_attention_barrier"),
    (worker, "reconcile_task", "idle_running_turn_completes_by_default"),
    (worker, "reconcile_task", "idle_turn_with_question_parks"),
    (worker, "reconcile_task", "idle_turn_after_answer_completes"),
    (worker, "reconcile_task", "agent_can_keep_working_after_question"),
    (worker, "reconcile_task", "question_survives_its_own_event_tail"),
    (worker, "reconcile_task", "ended_turn_finalizes_before_queued_input"),
    (main.Runtime, "ingest_fx_event", "event_handler_lifecycle"),
    (main.Runtime, "ingest_fx_event", "replayed_event_lines_are_inert"),
    (main.Runtime, "ingest_fx_event", "event_callbacks_are_invoked"),
    (main.Runtime, "meaningful_input", "meaningful_input_is_detected"),
    (main.Runtime, "ingest_fx_event", "terminal_noise_does_not_answer"),
    (main.Runtime, "ingest_fx_event", "terminal_noise_does_not_wake"),
    (main.Runtime, "ingest_fx_event", "completed_follow_up_records_input"),
    (main.Runtime, "ingest_fx_event", "finish_failure_is_reported"),
    (main.Runtime, "ingest_fx_event", "cancel_closes_event_iteration"),
    (main.Runtime, "ingest_fx_event", "cancel_while_awaiting_closes_iteration"),
    (main.Runtime, "ingest_fx_event", "busy_event_handler_retries"),
    (main.Runtime, "ingest_fx_event", "busy_event_handler_eventually_fails"),
    (main.Runtime, "ingest_fx_event", "event_handler_runs_stream"),
    (main.Runtime, "ingest_fx_event", "session_stream_error_fails_task"),
    (main.Runtime, "ingest_fx_event", "fatal_fx_error_fails_task"),
    (main.Runtime, "ingest_fx_event", "completion_without_turn_is_inert"),
    (main.Runtime, "ingest_fx_event", "event_sequence_survives_external_writer"),
    (main.Runtime, "is_runtime_echo", "runtime_echo_is_not_user_input"),
    (main.Runtime, "is_runtime_echo", "unwrapped_runtime_echo_is_recognized"),
    (main.Runtime, "ingest_fx_event", "one_submission_creates_one_barrier"),
    (main.Runtime, "task_context", "task_context_names_repo"),
    (main.Runtime, "task_context", "task_context_requests_pr"),
    (main.Runtime, "task_context", "task_context_updates_existing_pr"),
    (main.Runtime, "task_context", "task_context_uses_pr_count_decision"),
    (main.Runtime, "task_context", "task_context_has_pr_update_carveout"),
    (main.Runtime, "task_context", "task_context_names_multiple_repos"),
    (main.Runtime, "task_context", "single_repo_is_still_a_repo_list"),
    (main.Runtime, "task_context", "task_context_handles_no_repo"),
    (main.Runtime, "task_prompt", "first_prompt_carries_task_and_protocol"),
    (main.Runtime, "task_prompt", "first_prompt_carries_queued_input"),
    (main.Runtime, "task_prompt", "follow_up_prompt_sends_only_new_input"),
    (main.Runtime, "task_prompt", "every_prompt_names_question_protocol"),
]


@pytest.mark.parametrize("owner,capability,scenario", TASK_CONTRACTS, ids=[item[2] for item in TASK_CONTRACTS])
def test_retained_task_contract(owner, capability, scenario):
    _contract(owner, capability, scenario)
