/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRepositoryRouteImport } from './routes/_app.repository'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'
import { Route as AppChatsChatIdRouteImport } from './routes/_app.chats.$chatId'
import { Route as AppAgentsAgentIdApiRouteImport } from './routes/_app.agents.$agentId.api'
import { Route as AppAgentsAgentIdFilesRouteImport } from './routes/_app.agents.$agentId.files'
import { Route as AppChatsChatIdViewRouteImport } from './routes/_app.chats.$chatId.$view'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoryRoute = AppRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsChatIdRoute = AppChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdApiRoute = AppAgentsAgentIdApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppAgentsAgentIdRoute,
} as any)
const AppAgentsAgentIdFilesRoute = AppAgentsAgentIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppAgentsAgentIdRoute,
} as any)
const AppChatsChatIdViewRoute = AppChatsChatIdViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => AppChatsChatIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/repository': typeof AppRepositoryRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/chats/$chatId': typeof AppChatsChatIdRouteWithChildren
  '/agents/$agentId/api': typeof AppAgentsAgentIdApiRoute
  '/agents/$agentId/files': typeof AppAgentsAgentIdFilesRoute
  '/chats/$chatId/$view': typeof AppChatsChatIdViewRoute
}
export interface FileRoutesByTo {
  '/repository': typeof AppRepositoryRoute
  '/': typeof AppIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/chats/$chatId': typeof AppChatsChatIdRouteWithChildren
  '/agents/$agentId/api': typeof AppAgentsAgentIdApiRoute
  '/agents/$agentId/files': typeof AppAgentsAgentIdFilesRoute
  '/chats/$chatId/$view': typeof AppChatsChatIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/repository': typeof AppRepositoryRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/_app/chats/$chatId': typeof AppChatsChatIdRouteWithChildren
  '/_app/agents/$agentId/api': typeof AppAgentsAgentIdApiRoute
  '/_app/agents/$agentId/files': typeof AppAgentsAgentIdFilesRoute
  '/_app/chats/$chatId/$view': typeof AppChatsChatIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repository'
    | '/agents/$agentId'
    | '/chats/$chatId'
    | '/agents/$agentId/api'
    | '/agents/$agentId/files'
    | '/chats/$chatId/$view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/repository'
    | '/'
    | '/agents/$agentId'
    | '/chats/$chatId'
    | '/agents/$agentId/api'
    | '/agents/$agentId/files'
    | '/chats/$chatId/$view'
  id:
    | '__root__'
    | '/_app'
    | '/_app/repository'
    | '/_app/'
    | '/_app/agents/$agentId'
    | '/_app/chats/$chatId'
    | '/_app/agents/$agentId/api'
    | '/_app/agents/$agentId/files'
    | '/_app/chats/$chatId/$view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repository': {
      id: '/_app/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AppRepositoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/$chatId': {
      id: '/_app/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AppChatsChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/api': {
      id: '/_app/agents/$agentId/api'
      path: '/api'
      fullPath: '/agents/$agentId/api'
      preLoaderRoute: typeof AppAgentsAgentIdApiRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/files': {
      id: '/_app/agents/$agentId/files'
      path: '/files'
      fullPath: '/agents/$agentId/files'
      preLoaderRoute: typeof AppAgentsAgentIdFilesRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/chats/$chatId/$view': {
      id: '/_app/chats/$chatId/$view'
      path: '/$view'
      fullPath: '/chats/$chatId/$view'
      preLoaderRoute: typeof AppChatsChatIdViewRouteImport
      parentRoute: typeof AppChatsChatIdRoute
    }
  }
}

interface AppAgentsAgentIdRouteChildren {
  AppAgentsAgentIdApiRoute: typeof AppAgentsAgentIdApiRoute
  AppAgentsAgentIdFilesRoute: typeof AppAgentsAgentIdFilesRoute
}

const AppAgentsAgentIdRouteChildren: AppAgentsAgentIdRouteChildren = {
  AppAgentsAgentIdApiRoute: AppAgentsAgentIdApiRoute,
  AppAgentsAgentIdFilesRoute: AppAgentsAgentIdFilesRoute,
}

const AppAgentsAgentIdRouteWithChildren =
  AppAgentsAgentIdRoute._addFileChildren(AppAgentsAgentIdRouteChildren)

interface AppChatsChatIdRouteChildren {
  AppChatsChatIdViewRoute: typeof AppChatsChatIdViewRoute
}

const AppChatsChatIdRouteChildren: AppChatsChatIdRouteChildren = {
  AppChatsChatIdViewRoute: AppChatsChatIdViewRoute,
}

const AppChatsChatIdRouteWithChildren = AppChatsChatIdRoute._addFileChildren(
  AppChatsChatIdRouteChildren,
)

interface AppRouteChildren {
  AppRepositoryRoute: typeof AppRepositoryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRouteWithChildren
  AppChatsChatIdRoute: typeof AppChatsChatIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppRepositoryRoute: AppRepositoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRouteWithChildren,
  AppChatsChatIdRoute: AppChatsChatIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
