/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'
import { Route as AppThreadsThreadIdRouteImport } from './routes/_app.threads.$threadId'
import { Route as AppAgentsAgentIdFilesRouteImport } from './routes/_app.agents.$agentId.files'
import { Route as AppAgentsAgentIdSchedulesRouteImport } from './routes/_app.agents.$agentId.schedules'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsThreadIdRoute = AppThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdFilesRoute = AppAgentsAgentIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppAgentsAgentIdRoute,
} as any)
const AppAgentsAgentIdSchedulesRoute =
  AppAgentsAgentIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/agents/$agentId/files': typeof AppAgentsAgentIdFilesRoute
  '/agents/$agentId/schedules': typeof AppAgentsAgentIdSchedulesRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/agents/$agentId/files': typeof AppAgentsAgentIdFilesRoute
  '/agents/$agentId/schedules': typeof AppAgentsAgentIdSchedulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/_app/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/_app/agents/$agentId/files': typeof AppAgentsAgentIdFilesRoute
  '/_app/agents/$agentId/schedules': typeof AppAgentsAgentIdSchedulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/$agentId'
    | '/threads/$threadId'
    | '/agents/$agentId/files'
    | '/agents/$agentId/schedules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$agentId'
    | '/threads/$threadId'
    | '/agents/$agentId/files'
    | '/agents/$agentId/schedules'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/agents/$agentId'
    | '/_app/threads/$threadId'
    | '/_app/agents/$agentId/files'
    | '/_app/agents/$agentId/schedules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$threadId': {
      id: '/_app/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/files': {
      id: '/_app/agents/$agentId/files'
      path: '/files'
      fullPath: '/agents/$agentId/files'
      preLoaderRoute: typeof AppAgentsAgentIdFilesRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/schedules': {
      id: '/_app/agents/$agentId/schedules'
      path: '/schedules'
      fullPath: '/agents/$agentId/schedules'
      preLoaderRoute: typeof AppAgentsAgentIdSchedulesRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
  }
}

interface AppAgentsAgentIdRouteChildren {
  AppAgentsAgentIdFilesRoute: typeof AppAgentsAgentIdFilesRoute
  AppAgentsAgentIdSchedulesRoute: typeof AppAgentsAgentIdSchedulesRoute
}

const AppAgentsAgentIdRouteChildren: AppAgentsAgentIdRouteChildren = {
  AppAgentsAgentIdFilesRoute: AppAgentsAgentIdFilesRoute,
  AppAgentsAgentIdSchedulesRoute: AppAgentsAgentIdSchedulesRoute,
}

const AppAgentsAgentIdRouteWithChildren =
  AppAgentsAgentIdRoute._addFileChildren(AppAgentsAgentIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRouteWithChildren
  AppThreadsThreadIdRoute: typeof AppThreadsThreadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRouteWithChildren,
  AppThreadsThreadIdRoute: AppThreadsThreadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
